### ISSUE TITLE
大佬可不可以考虑把配方初期品质调整为可自定义？

### ISSUE THREAD

**Issue by superjump22** [Tnze/ffxiv-best-craft#10]
就是这个地方：
[![1.png](https://i.postimg.cc/htfyN10V/1.png)](https://postimg.cc/3kQFvpVw)
只能通过改下面的素材的品质来调整，这在使用【本地数据】的时候的确很方便
但是我发现在使用【Xivapi】试玩6.4新配方的时候，底下的素材没有全部列出来，导致这里无法调整初期品质，只能0和1/2二选一
所以我想干脆开放成可以修改好了？这样可行吗？

顺带一提，反馈里的【QQ频道】二维码过期了~

**Comment by Tnze** [comment]
1. 使用Xivapi时存在材料列表不全的Bug
2. 希望能允许手动调整初期品质
3. QQ频道链接已失效

关于2.直接输入初期品质的功能是可以实现的，目前仅在自定义配方中开启，可以加一个切换开关。

关于1.我晚点看一下，不知道问题出在这边还是Xivapi。

关于3.下个版本我更新一下，感谢提醒。

**Comment by superjump22** [comment]
好的感谢，原来可以自定义配方吗？PC版我没找到，你说的是不是网页版？

**Comment by Tnze** [comment]
> 好的感谢，原来可以自定义配方吗？PC版我没找到，你说的是不是网页版？

在配方搜索框右边有自定义按钮

**Comment by superjump22** [comment]
好的，了解！

**Comment by Tnze** [comment]
完了，忘记更新QQ频道链接了
