### ISSUE TITLE
大佬好，在使用过程中出现了问题

### ISSUE THREAD

**Issue by Anti-World** [Tnze/ffxiv-best-craft#11]
鲶鱼精的蛮族任务道具“游牧民风格的商品”在使用求解器时会出现输出结果无任何步骤的现象
![image](https://github.com/Tnze/ffxiv-best-craft/assets/83451822/a8c79a28-fa77-453a-9b96-1de275f9f210)

**Comment by Tnze** [comment]
用深度优先的话可以秒出结果哦

**Comment by Anti-World** [comment]
> 

我用的是广度优先v2，深度优先我用了好像不能推满品质，还是我用的方法不对？

**Comment by Anti-World** [comment]
> 我试了跟你完全相同的属性，用神速技巧两步就能推满呀

![image](https://github.com/Tnze/ffxiv-best-craft/assets/83451822/a2710071-6b50-4646-9763-8a09da422106)
很奇怪，我用了深度优先，只能推出这样的

**Comment by Tnze** [comment]
你等级怎么变低了？上一张图还是90级

如果只有65级的话确实用深度优先推不满，广度不行的话只能试试动规了。

要不试试向导？

**Comment by Tnze** [comment]
有一个好消息，你这个配方不需要推满品质，因为它没有对应的HQ物品

**Comment by Anti-World** [comment]
> 你等级怎么变低了？上一张图还是90级
> 
> 如果只有65级的话确实用深度优先推不满，广度不行的话只能试试动规了。
> 
> 要不试试向导？

其实最开始就是在这个等级用广度优先发现的不行，然后试了别的职业也这样，不过能用就行了
啊还有一个问题，反馈的那个qq频道邀请过期了

**Comment by Tnze** [comment]
> 啊还有一个问题，反馈的那个qq频道邀请过期了

前一个issue提到了，已经更新了但是没来得及推送版本，应该马上就好
