### ISSUE TITLE
90级制作92级配方提示Player level is lower than the recipe's requirement.

### ISSUE THREAD

**Issue by Beryllium-10** [Tnze/ffxiv-best-craft#14]
先在Gearsets里选择Inherit from default（此时Lv默认为100）
然后取消，选成手动输入
输入等级为90
在Recipes里搜索92级配方
comfirm后会报错
Player level is lower than the recipe's requirement.
具体是设置厨师 等级90 搜索Mez，选择Mezcal-marinated Swampmonk的时候
reload之后重新在Recipes里搜索并Confrim就可以正确进入模拟器

**Comment by Tnze** [comment]
输入90的时候，你是先输入9，再输入0。
当你输入9的时候等级已经实时更新了，然后出现了等级不足的错误

**Comment by Tnze** [comment]
如果是用光标选择90的0再输入2，就不会触发这个问题
