### ISSUE TITLE
客户端Gearsets Lv.最大为90

### ISSUE THREAD

**Issue by ChenyeXie** [Tnze/ffxiv-best-craft#15]
作者您好。

如标题所述，我在使用BestCraft v0.15.7客户端时，Gearsets中Crafter Attributes的Lv.最高只能设置为90，无论是键盘输入还是点击“+”都不行。
![image](https://github.com/user-attachments/assets/4c70dd9b-33cb-47e8-a0f3-40e58f6eb551)

网页版没有这个问题，请问是什么原因？

**Comment by Tnze** [comment]
客户端目前最新版本适配国服6.0，玩家等级最高为90级。

网页版<https://tnze.yyyy.games/>同上

网页版7.0开发分支<https://tnze.yyyy.games/dawntrail/>适配国际服7.0，玩家等级最高100。

如果玩国际服，使用网页版7.0版即可。

当然也可以自行编译适配7.0的客户端版本，但是由于7.0求解器网页版已经足够好，个人感觉意义不大。
