### ISSUE TITLE
[Bug]  勾选掌握或坚信后求解器不会给出任何结果

### ISSUE THREAD

**Issue by FYWinds** [Tnze/ffxiv-best-craft#2]
![image](https://user-images.githubusercontent.com/74457127/165009357-b6226017-7c97-4ca5-92c0-54eadea8380c.png)
如上图

**Comment by Tnze** [comment]
由于算法限制，坚信暂时需要手动起手。把进展条推到差一个技能推满的时候才会出结果

**Comment by Tnze** [comment]
具体使用方法可以阅读Gitee上发行版中v0.2.0版本更新日志中《关于坚信起手的说明》

未来版本中计划内置一些坚信起手并自动搜索最优解
