### ISSUE TITLE
设计页希望支持 鼠标指针悬浮在技能按钮上，显示技能名标签 的功能

### ISSUE THREAD

**Issue by TioaChan** [Tnze/ffxiv-best-craft#3]
be like 
![image](https://user-images.githubusercontent.com/8370450/165103206-d75d1468-a0b7-49d8-9dee-31262831a4fb.png)

**Comment by Tnze** [comment]
不如显示完整的技能介绍（？

**Comment by Tnze** [comment]
v0.5.3已支持
