### ISSUE TITLE
希望添加页面缩放设置或者高分屏支持

### ISSUE THREAD

**Issue by daniellonetree** [Tnze/ffxiv-best-craft#4]
17寸2K看着费劲，加一个页面缩放设置，整体放大或缩小UI

**Comment by Tnze** [comment]
自己右键exe属性里设置一下？我自己也用的2K屏，蛮正常的啊

**Comment by Tnze** [comment]
你看https://bestcraft.tnze.me 有没有问题

**Comment by daniellonetree** [comment]
网页缩放没有问题，EXE我回头尝试设置一下，谢谢解惑
